version: 2

jobs:
  test:
    docker:
      - image: node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm test
  coverage:
    docker:
      - image: node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run coverage
      - store_artifacts:
          path: coverage
  
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t lucasbrocheton/gameoflife-nge-lbr .
      - run: docker save -o image.tar lucasbrocheton/gameoflife-nge-lbr
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  push:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: docker load -i /tmp/workspace/image.tar
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker push lucasbrocheton/gameoflife-nge-lbr

workflows:
  version: 2
  workflow:
    jobs:
      - test
      - coverage
      - build:
          requires:
            - test
            - coverage
      - push:
          requires:
            - build
