version: 2

jobs:
  test:
    docker:
      - image: node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run coverage
      - store_artifacts:
          path: coverage
  
  build:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker build -t lucasbrocheton/gameoflife-nge-lbr .
      - run: docker push lucasbrocheton/gameoflife-nge-lbr

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test

