version: 2

jobs:
  test:
    docker:
      - image: node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm test
  coverage:
    docker:
      - image: node:14
    working_directory: ~/repo
    steps:
      - run: npm install
      - run: npm run coverage
      - store_artifacts:
          path: coverage
  build:
    docker:
      - image: node:14
    working_directory: ~/repo
    steps:
      - run: npm build
