version: 2

jobs:
  test:
    docker:
      - image: node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run coverage
      - store_artifacts:
          path: coverage
  build:
    docker:
      - image: node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm build

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build
